<?php
/**
 * Created by PhpStorm.
 * User: vuquangthinh
 * Date: 1/7/2016
 * Time: 8:38 AM
 */

namespace common\assets;

use yii\web\AssetBundle;

class AdminLTEAsset extends AssetBundle
{
    public $sourcePath = '@vendor/almasaeed2010/adminlte';

    public static $skin = 'skin-blue';

    public $css = [
        'plugins/iCheck/all.css',
        'dist/css/AdminLTE.min.css',
    ];

    public $js = [
        'plugins/iCheck/icheck.min.js',
        'dist/js/app.min.js',
    ];

    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
        'yii\bootstrap\BootstrapPluginAsset',
        'rmrevin\yii\fontawesome\AssetBundle',
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->css[] = 'dist/css/skins/' . self::$skin . '.min.css';
    }
}