<?php

namespace common\widgets;

use yii\grid\GridView as GridViewBase;

class GridView extends GridViewBase
{
    public $layout = "<div class=\"box\"><div class=\"box-header with-border\">{summary} <span class=\"box-tools\">{pager}</span></div>\n{items}\n<div class=\"box-footer clearfix text-right\">{pager}</div>\n</div>";
    public function init()
    {
    	$this->tableOptions = ['class' => 'table table-hover no-margin'];
        $this->pager['options'] = ['class' => 'pagination pagination-sm pull-right no-margin'];
        parent::init(); // TODO: Change the autogenerated stub
    }
}